# Generated by Django 3.2 on 2022-08-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nglib', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchstats',
            old_name='frequency',
            new_name='amount',
        ),
    ]
